// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-KVTnMo870NnvuzFgIZMWR1CoPIIfZjw',
    appId: '1:332602269086:web:14728bb8ce06a27ec5ca8f',
    messagingSenderId: '332602269086',
    projectId: 'mobile-app-fbla',
    authDomain: 'mobile-app-fbla.firebaseapp.com',
    storageBucket: 'mobile-app-fbla.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbRNRWCmb5YLwSn5r4xXWcWkHd1nUw5gA',
    appId: '1:332602269086:android:47240cfdb6e4ce0bc5ca8f',
    messagingSenderId: '332602269086',
    projectId: 'mobile-app-fbla',
    storageBucket: 'mobile-app-fbla.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM2ma3urZR9rGtchwOiD73oB6Rjw8CJOI',
    appId: '1:332602269086:ios:241d4e6ecd27c500c5ca8f',
    messagingSenderId: '332602269086',
    projectId: 'mobile-app-fbla',
    storageBucket: 'mobile-app-fbla.appspot.com',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM2ma3urZR9rGtchwOiD73oB6Rjw8CJOI',
    appId: '1:332602269086:ios:241d4e6ecd27c500c5ca8f',
    messagingSenderId: '332602269086',
    projectId: 'mobile-app-fbla',
    storageBucket: 'mobile-app-fbla.appspot.com',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-KVTnMo870NnvuzFgIZMWR1CoPIIfZjw',
    appId: '1:332602269086:web:792cb383ff94a329c5ca8f',
    messagingSenderId: '332602269086',
    projectId: 'mobile-app-fbla',
    authDomain: 'mobile-app-fbla.firebaseapp.com',
    storageBucket: 'mobile-app-fbla.appspot.com',
  );

}